version: "1"
services: #Khởi tạo service
    php:
        build: #Chỉ định file xây dựng image cho service php ()
            context: .
            dockerfile: Dockerfile
        volumes: #Định nghĩa nơi lưu trữ chia sẻ giữa ứng dụng và docker container.
            - .:/var/www/html # ánh xạ thư mục ./laravel (máy chủ) tới /var/www/html (máy ảo) (đảm bảo rằng khi container tắt đi và bật lại sẽ không mất dữ liệu)
        environment:
            - APP_NAME=Laravel
            - APP_ENV=local
            - APP_KEY=base64:mtpMOefOGwji0sWbWONS6qUFtX0JGm80kbahC5PKTYs=
            - APP_DEBUG=true
            - APP_URL=http://localhost
            - LOG_CHANNEL=stack
            - LOG_DEPRECATIONS_CHANNEL=null
            - LOG_LEVEL=debug
            - DB_CONNECTION=mysql
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=ticket
            - DB_USERNAME=thang
            - DB_PASSWORD=Thang1610@
            - BROADCAST_DRIVER=redis
            - CACHE_DRIVER=redis
            - FILESYSTEM_DISK=local
            - QUEUE_CONNECTION=redis
            - SESSION_DRIVER=redis
            - SESSION_LIFETIME=120
            - MEMCACHED_HOST=127.0.0.1
            - REDIS_HOST=redis
            - REDIS_PASSWORD=null
            - REDIS_PORT=6379
            - MAIL_MAILER=smtp
            - MAIL_HOST=smtp.gmail.com
            - MAIL_PORT=587
            - MAIL_USERNAME=nguyenhuuthangc7@gmail.com
            - MAIL_PASSWORD=vxqvwefsdmclymwi
            - MAIL_ENCRYPTION=null
            - MAIL_FROM_ADDRESS="hello@example.com"
            - MAIL_FROM_NAME="${APP_NAME}"
            - AWS_ACCESS_KEY_ID=
            - AWS_SECRET_ACCESS_KEY=
            - AWS_DEFAULT_REGION=us-east-1
            - AWS_BUCKET=
            - AWS_USE_PATH_STYLE_ENDPOINT=false
            - PUSHER_APP_ID=
            - PUSHER_APP_KEY=
            - PUSHER_APP_SECRET=
            - PUSHER_HOST=
            - PUSHER_PORT=443
            - PUSHER_SCHEME=https
            - PUSHER_APP_CLUSTER=mt1
            - VITE_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
            - VITE_PUSHER_HOST="${PUSHER_HOST}"
            - VITE_PUSHER_PORT="${PUSHER_PORT}"
            - VITE_PUSHER_SCHEME="${PUSHER_SCHEME}"
            - VITE_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
            - GOOGLE_RECAPTCHA_KEY="6LdOUYEoAAAAAAsQAZvp4cUx5mBmiZLylZy_DoCQ"
            - GOOGLE_RECAPTCHA_SECRET="6LdOUYEoAAAAAPiCVoaqrzUsyF62Rnwlvb5ektDr"
            - CLOUDINARY_CLOUD_NAME="dstuqb1iv"
            - CLOUDINARY_API_KEY="656214999469622"
            - CLOUDINARY_API_SECRET="-2GDm-lDd_sT37jGQiuhR94jYUE"
            - CLOUDINARY_SECURE_URL=true
            - CLOUDINARY_URL=cloudinary://656214999469622:-2GDm-lDd_sT37jGQiuhR94jYUE@dstuqb1iv
            - CLOUDINARY_UPLOAD_PRESET=wqddm323
            - CLOUDINARY_NOTIFICATION_URL=
        ports:
            - "7000:9000" #ánh xạ port 9000 (máy chủ) tới port 9000 (máy ảo)

    mysql:
        image: mysql:8.0.29-oracle
        ports:
            - "3308:3306" #port 3308 (máy chủ) tránh trùng với port của mysql có trên máy (3307)
        volumes:
            - mysql:/var/lib/mysql
        cap_add:
            - SYS_NICE
        environment:
            MYSQL_DATABASE: ticket
            MYSQL_USER: thang
            MYSQL_PASSWORD: Thang1610@
            MYSQL_ROOT_PASSWORD: Thang1610@

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        depends_on:
            - mysql
        environment:
            PMA_HOSTS: mysql
            PMA_PORT: 3306
            PMA_USER: thang
            PMA_PASSWORD: Thang1610@

    redis:
        image: redis:7.2-alpine
        ports:
            - "6379:6379"
        command: redis-server
        volumes:
            - redis:/data

    nginx:
        image: "nginx:stable"
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
