version: "1"
services: #Khởi tạo service
    php:
        build: #Chỉ định file xây dựng image cho service php ()
            context: .
            dockerfile: Dockerfile
        volumes: #Định nghĩa nơi lưu trữ chia sẻ giữa ứng dụng và docker container.
            - .:/var/www/html # ánh xạ thư mục ./laravel (máy chủ) tới /var/www/html (máy ảo) (đảm bảo rằng khi container tắt đi và bật lại sẽ không mất dữ liệu)
        env_file:
            ./.env
        ports:
            - "9000:9000" #ánh xạ port 9000 (máy chủ) tới port 9000 (máy ảo)

    mysql:
        image: mysql:8.0.29-oracle
        ports:
            - "3308:3306" #port 3308 (máy chủ) tránh trùng với port của mysql có trên máy (3307)
        volumes:
            - ./mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: ticket
            MYSQL_USER: thang
            MYSQL_PASSWORD: Thang1610@
            MYSQL_ROOT_PASSWORD: Thang1610@

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        depends_on:
            - mysql
        environment:
            PMA_HOSTS: mysql
            PMA_PORT: 3306
            PMA_USER: thang
            PMA_PASSWORD: Thang1610@

    redis:
        image: redis:7.2-alpine
        ports:
            - "6379:6379"
        command: redis-server
        volumes:
            - ./data/redis:/data

    nginx:
        image: "nginx:stable"
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
